name: ROS test

on:
  push:
    branches:
    - main

jobs:
  Ros_test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Build docker
        uses: actions/checkout@v2
        run: cd ${{github.workspace}} && docker build .