name: CI

on:
  push:
    branches:
    - main

jobs:
  CI:
    runs-on: [ubuntu-20.04]

    steps:
    - name: Setup ros
    - uses: actions/checkout@v3

    - name: setup environment
      uses: actions/setup-node@v3
    	run: |
    		sudo apt update
    		sudo apt install ros-noetic-core
    		source /opt/ros/noetic/setup.bash