name: CI

on:
  push:
    branches:
    - main

jobs:
  workflow-command-job:
    runs-on: ubuntu-latest
    steps:
      - name: toggle workflow command echoing
        run: |
          echo "Hello"
          echo "world"