name: ROS test

on:
  push:
    branches:
    - main

jobs:
  Ros_test:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
    - uses: actions/checkout@v2

    - name: Check repository
      run: cd src
    
