name: ROS test

on:
  push:
    branches:
    - main

jobs:
  Ros_test:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install ROS Noetic
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get -y install python3-catkin-tools


    - name: Check repository
      run: |
        cd src
        ls
    
