name: ROS test

on:
  push:
    branches:
    - main

jobs:
  Ros_test:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build Docker Image
      uses: docker/build-push-action@v3
      with:
        # use tags if multiple images are running in parallel
        file: .github/workflows/Dockerfile 

    - name: Compile with Catkin Tools
      uses: addnab/docker-run-action@v3
      with:
        options:  -v ${{github.workspace}}/src:/ros/src/  # only mount source here
        run: |
          catkin config --workspace /ros/ --init --extend /opt/ros/noetic --cmake-args -DCMAKE_EXPORT_COMPILE_COMMANDS=ON
          catkin build --workspace /ros/ --interleave-output --verbose

    - name: Source workspace
      shell: bash
      run: |
        cd src
        ls

    
