name: ROS test

on:
  push:
    branches:
    - main

jobs:
  Ros_test:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build Docker Image
      uses: docker/build-push-action@v3
      with:
        file: .github/workflows/Dockerfile

    - name: Source workspace
      shell: bash
      run: ls

    
