name: CI

on:
  push:
    branches:
    - main

jobs:
  CI:
    runs-on: [ubuntu-20.04]

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Run echo
        uses: actions/checkout@v1
    	  run: echo "Hello"